#!/bin/bash

# This is the NoteLab startup script for Unix based systems (Linux and Solaris).  It is used to start 
# NoteLab with specific virtual machine arguments as well as NoteLab specific arguments.  These arguments are those 
# that are specified by the user using NoteLab's settings control.

# Please DO NOT EDIT this file as it is responsible for starting NoteLab.  If this file is corrupted NoteLab
# may not start.  If you want to edit this file, it is advised that you first make a backup.

# NoteLab's home directory
NOTELAB_HOME=${HOME}/.NoteLab

# Determine the shell script that serves to initialize the environment for the Java virtual machine and NoteLab.
INIT_FILE=${NOTELAB_HOME}/initenv.sh

# If the file above exists source it so that the environment is initialized.
if [ -e "${INIT_FILE}" ]; then 
  source "${INIT_FILE}"; 
fi

# Determine the installation directory, i.e. the directory that contains this script.  
# '$0' stores the absolute path to this script and the 'dirname' command returns the 
# absolute path of the parent directory of '$0'.
INSTALL_DIR=`dirname "$0"`

# Move to the installation directory
cd "${INSTALL_DIR}"

# Start the Java virtual machine with the given VM arguments and instruct it to load NoteLab with NoteLab's arguments
java ${NOTELAB_VM_ARGS} -DNOTELAB_SETTINGS_FILENAME="${INIT_FILE}" -cp .:./info:./jar/PDFRenderer.jar:./jar/iText.jar:"${CLASSPATH}" noteLab.util.StartupUtilities ${NOTELAB_ARGS} $*

# The variable ${NOTELAB_VM_ARGS} specifies the initial amount and maximum amount of memory that 
# should be given to the virtual machine.  If NoteLab fails to start from the invocation of 'java' 
# above, it may because there is not enough memory to meet NoteLab's request.  Thus start NoteLab 
# without requiring a specific amount of memory.

# The variable '$?' stores the exit status of the previous command run.  If the exit status of 
# 'java' is not 0, an error has occured when 'java' was run.
if [ $? != 0 ]; then
  echo ""
  echo "The system would not allow NoteLab to start with its requested amount of maximum or initial memory."
  echo "The most likely cause is that there is not enough memory available."
  echo "NoteLab will now start without requiring any special amount of memory."
  java -DNOTELAB_SETTINGS_FILENAME="${INIT_FILE}" -cp .:./info:./jar/PDFRenderer.jar:./jar/iText.jar:"${CLASSPATH}" noteLab.util.StartupUtilities --lookAndFeel Nimbus ${NOTELAB_ARGS} $*
  if [ $? != 0 ]; then
    echo ""
    echo "NoteLab could not be started.  See the messages above to find the cause of the failure."
    echo "For assistance, NoteLab's head developer, Dominic Kramer, can be contacted at kramerd@users.sourceforge.net."
    echo "Please include any messages above and the messages below for the best support."
    java -version
  fi
fi
