@echo off

REM This is the NoteLab startup script for Windows based systems.  It is used to start NoteLab with specific
REM virtual machine arguments as well as NoteLab specific arguments.  These arguments are those that are
REM specified by the user using NoteLab's settings control.

REM Please DO NOT EDIT this file as it is responsible for starting NoteLab.  If this file is corrupted NoteLab
REM may not start.  If you want to edit this file, it is advised that you first make a backup.

REM Determine the batch file that serves to initialize the environment for the Java virtual machine and NoteLab.
SET INIT_FILE=%HOMEDRIVE%%HOMEPATH%\.NoteLab\initenv.bat

REM If the file above exists invoke it so that the environment is initialized.
IF EXIST "%INIT_FILE%" CALL "%INIT_FILE%"

REM Get the installation directory, i.e. the current working directory
SET INSTALL_DIR=%CD%

REM Move to the installation directory
cd "%INSTALL_DIR%"

REM Start the Java virtual machine with the given VM arguments and instruct it to load NoteLab with NoteLab's arguments
java %NOTELAB_VM_ARGS% -DNOTELAB_SETTINGS_FILENAME="%INIT_FILE%" -cp .;./info;./jar/PDFRenderer.jar;./jar/iText.jar;"%CLASSPATH%" noteLab.util.StartupUtilities %NOTELAB_ARGS% %*

REM The command 'IF NOT ERRORLEVEL 1' returns true if the variable ERRORLEVEL is not greater than or 
REM equal to 1, i.e. is less than 1.

REM If the errorlevel is set to 0 then the invocation of 'java' above returned with no errors.
REM Thus the script should just finish.  Otherwise, NoteLab could not be started and 
REM further work should be done to start NoteLab.
IF NOT ERRORLEVEL 1 GOTO Finish

REM At startup NoteLab requests a specific amout of initial and maximum memory.  These values are 
REM stored in the variable %NOTELAB_VM_ARGS%.  If NoteLab fails to start from the invocation 
REM of 'java' above, it may because there is not enough memory to meet NoteLab's request.  
REM Thus start NoteLab without requiring a specific amount of memory.

ECHO The system would not allow NoteLab to start with its requested amount of maximum or initial memory.
ECHO The most likely cause is that there is not enough memory available.
ECHO NoteLab will now start without requiring any special amount of memory.

java -DNOTELAB_SETTINGS_FILENAME="%INIT_FILE%" -cp .;./info;./jar/PDFRenderer.jar;./jar/iText.jar;"%CLASSPATH%" noteLab.util.StartupUtilities --lookAndFeel Nimbus %NOTELAB_ARGS% %*

REM If the errorlevel is set to 0 then this invocation of 'java' was successful and the script should 
REM just finish.  Otherwise a message should be printed stating that NoteLab could not be started.
IF NOT ERRORLEVEL 1 GOTO Finish

ECHO NoteLab could not be started.  See the messages above to find the cause of the failure.
ECHO For assistance, NoteLab's head developer, Dominic Kramer, can be contacted at kramerd@users.sourceforge.net.
ECHO Please include any messages above and the messages below for the best support.
java -version

REM The label that marks the part of the script that cleans up the environment variables.
:Finish

REM Reset all of the constructed variables
set INIT_FILE=
set NOTELAB_VM_ARGS=
set NOTELAB_ARGS=
set INSTALL_DIR=
