#!/bin/sh

# This is the NoteLab uninstall script for Unix based systems 
# (Linux, Solaris, and MacOS X).  

# Please DO NOT EDIT this file as it is responsible for uninstalling NoteLab.  
# If this file is corrupted you may not be able to uninstall NoteLab.
# If you want to edit this file, it is advised that you first make a backup.

# NoteLab's home directory
NOTELAB_HOME=$HOME/.NoteLab

# Determine the file that contains information about the installation directory
INSTALL_DIR_ENV=$NOTELAB_HOME/init_install_env.sh

# Store the current directory
CUR_DIR=.

# If the file exists source it so that the variable 'NOTELAB_INSTALL_DIR' 
# contains the installation directory.
if [ -e $INSTALL_DIR_ENV ]; then 
  source $INSTALL_DIR_ENV
  # Change the current directory to the install directory
  CUR_DIR=$NOTELAB_INSTALL_DIR
fi

# Start the Java virtual machine and have it load the uninstaller
java -cp $CUR_DIR:info noteLab.gui.uninstall.UninstallFrame

# Finish up by removing the installation directory
rmdir $NOTELAB_INSTALL_DIR
