@echo off

REM This is the NoteLab uninstall script for Windows based systems.

REM Please DO NOT EDIT this file as it is responsible for uninstall NoteLab.  
REM If this file is corrupted you may not be able to uninstall NoteLab. 
REM If you want to edit this file, it is advised that you first make a backup.

REM Determine the file that contains information about the installation directory
set INSTALL_DIR_ENV="%HOMEDRIVE%%HOMEPATH%\.NoteLab\init_install_env.bat"

REM If the file above exists invoke it so that the variable 
REM 'NOTELAB_INSTALL_DIR' contains the installation directory.
IF EXIST %INSTALL_DIR_ENV% CALL %INSTALL_DIR_ENV%

REM Store the current directory
set CUR_DIR=.

REM If the install directory has been stored, set it as the current directory
IF EXIST %INSTALL_DIR_ENV% set CUR_DIR=%NOTELAB_INSTALL_DIR%

REM Start the Java virtual machine and have it load the uninstaller
java -cp %CUR_DIR%;info noteLab.gui.uninstall.UninstallFrame

REM Finish up by removing the installation directory
REM First change to the home directory so the install directory is not in use.
cd %HOMEDRIVE%%HOMEPATH%
rmdir %NOTELAB_INSTALL_DIR%

REM Reset all of the constructed variables
set INSTALL_DIR_ENV=
set NOTELAB_INSTALL_DIR=
set CUR_DIR=
